Add Dhrystone and CoreMark benchmarks to the simulation environment.
git-svn-id: http://opencores.org/ocsvn/openmsp430/openmsp430/trunk@145 c36ddccb-d6af-41aa-abd5-588c0c1d0201

diff --git a/core/sim/rtl_sim/run/run_c b/core/sim/rtl_sim/run/run_c
--- a/core/sim/rtl_sim/run/run_c
+++ b/core/sim/rtl_sim/run/run_c
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+###############################################################################
+#                               Configuration                                 #
+###############################################################################
+
 # Enable/Disable waveform dumping
 OMSP_NODUMP=0
 export OMSP_NODUMP
@@ -14,6 +18,35 @@ export OMSP_NODUMP
 OMSP_SIMULATOR=iverilog
 export OMSP_SIMULATOR
 
+###############################################################################
+#                            Parameter Check                                  #
+###############################################################################
+EXPECTED_ARGS=1
+if [ $# -ne $EXPECTED_ARGS ]; then
+    echo "ERROR    : wrong number of arguments"
+    echo "USAGE    : run_c <test name>"
+    echo "Example  : run_c sandbox"
+    echo ""
+    echo "Available tests:"
+    echo -ne "                 "
+    ls ../src-c/
+    echo ""
+  exit 1
+fi
 
-../bin/msp430sim_c sandbox
+###############################################################################
+#                     Check if the required files exist                       #
+###############################################################################
+softdir=../src-c/$1;
 
+if [ ! -e $softdir ]; then
+    echo "ERROR: test directory doesn't exist: $softdir"
+    echo ""
+    echo "Available tests:"
+    echo -ne "                 "
+    ls ../src-c/
+    echo ""
+    exit 1
+fi
+
+../bin/msp430sim_c $1
